# 과제 1

## Matrix 구현 
1. Linear Regression에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해주세요.
2. LSE에서 쓰이는 Loss Function, **MSE**를 행렬로 구현해 출력해주세요.

### Data Load

In [ ]:
import pandas as pd 
data = pd.read_csv("/content/drive/MyDrive/ToBig's/week2/assignment1.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data.head()

    y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [ ]:
data.shape     # y:(9,1), X:(9,5)

(9, 6)

In [ ]:
data

    y    x1    x2  x3    x4    x5
0  10  38.9  64.7   4   868  59.7
1  13  41.6  45.3  -4   957  61.4
2  11  39.7  74.1   8   786  61.0
3   7  37.3  48.0  19   984  67.5
4  10  39.5  51.9   6   700  57.2
5   9  37.4  53.6  -5  1037  58.8
6   9  35.1  71.4   3   986  58.6
7   6  38.8  58.3   6   819  59.2
8   5  36.6  52.6 -19   791  54.4

In [ ]:
X = data.drop(["y"], axis=1)
y = data.y

In [ ]:
# Matrix 계산을 위해 X와 y를 numpy 형태로 바꾸어줍니다. 
X = X.to_numpy()
y = y.to_numpy()

In [ ]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [ ]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5])

### 1. Normal Equation

In [ ]:
import numpy as np
from numpy.linalg import inv

In [ ]:
def estimate_beta(X, y):
    designX = np.insert(X, 0, 1, axis=1) 
    beta_hat = inv(designX.T @ designX) @ designX.T @ y
    
    return beta_hat

In [ ]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)
pred

array([10.21307892, 12.25991477, 10.68709119,  6.87086032,  8.39142371,
        9.47262921,  7.8707847 ,  9.11986574,  5.11435143])

In [ ]:
print(model.intercept_)   # intercept
print(model.coef_)   # 추정된 회귀계수 (intercept 제외)

-39.24473678135655
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]

### 2. MSE

In [ ]:
def MSE(X, y, beta_hat):
    designX = np.insert(X, 0, 1, axis=1)
    y_pred = designX @ beta_hat
    print("실제 y값 :", y)
    print("예측 y값 :", y_pred)
    mse = ((y - y_pred)**2).mean()
    
    return mse

In [ ]:
MSE(X, y, estimate_beta(X, y))

실제 y값 : [10 13 11  7 10  9  9  6  5]
예측 y값 : [10.21307892 12.25991477 10.68709119  6.87086032  8.39142371  9.47262921
  7.8707847   9.11986574  5.11435143]

1.6155977229019138